name: build.yml
on: workflow_dispatch

jobs:

  # =======================================================================
  # Job : Build et push des images Docker vers GHCR
  # =======================================================================
  build-images:
    name: Build Images Docker
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # --- Checkout du code ---
      - name: Checkout du code
        uses: actions/checkout@v6

      # --- Configurer Docker Buildx (builder avancé) ---
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      # --- Se connecter au GitHub Container Registry ---
      - name: Login GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Build et push de l'image backend ---
      - name: Build & Push Backend
        uses: docker/build-push-action@v7
        with:
          context: ./api
          file: ./api/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/seyjax2/yapuka-correction-seyjax/backend:latest
            ghcr.io/seyjax2/yapuka-correction-seyjax/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Build et push de l'image frontend ---
      - name: Build & Push Frontend
        uses: docker/build-push-action@v7
        with:
          context: ./front
          file: ./front/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/seyjax2/yapuka-correction-seyjax/frontend:latest
            ghcr.io/seyjax2/yapuka-correction-seyjax/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max